# These are supported funding model platforms

github: [evilfeonix]
# patreon: evilfeonix
open_collective: evilfeonix-project
ko_fi: evilfeonix
tidelift: npm/evilfeonix-library
# community_bridge: evilfeonix-cloud
liberapay: evilfeonix
# issuehunt: evilfeonix
# lfx_crowdfunding: evilfeonix-infra
# polar: evilfeonix
buy_me_a_coffee: https://buymeacoffee.com/evilfeonix
thanks_dev: evilfeonix
custom: ['https://paypal.me/evilfeonix']
